# Generated by Django 4.2.7 on 2026-04-03 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estimated_days_min', models.IntegerField(default=1)),
                ('estimated_days_max', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'shipping_methods',
            },
        ),
    ]
