# Generated by Django 4.2.7 on 2026-05-08 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Assistant ShopWave', max_length=100)),
                ('welcome_message', models.TextField(default="Bonjour ! Je suis l'assistant ShopWave. Comment puis-je vous aider aujourd'hui ?")),
                ('fallback_message', models.TextField(default="Je n'ai pas compris votre demande. Souhaitez-vous être mis en relation avec un conseiller humain ?")),
                ('escalation_message', models.TextField(default='Je vous mets en relation avec un conseiller. Notre équipe vous répondra dans les plus brefs délais.')),
                ('is_active', models.BooleanField(default=True)),
                ('human_support_email', models.EmailField(default='support@shopwave.tn', max_length=254)),
                ('human_support_hours', models.CharField(default='Lun-Ven, 9h-18h', max_length=100)),
                ('avatar_color', models.CharField(default='#E63946', max_length=10)),
                ('auto_open_delay', models.IntegerField(default=0, help_text='Secondes avant ouverture automatique (0 = désactivé)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Chatbot',
                'db_table': 'chatbot_config',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, help_text='For anonymous users', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('escalated', 'Escaladée vers support'), ('resolved', 'Résolue'), ('abandoned', 'Abandonnée')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('rating_comment', models.TextField(blank=True)),
                ('escalated_to_email', models.EmailField(blank=True, max_length=254)),
                ('tags', models.JSONField(default=list)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='SVG path or icon name', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'faq_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('message', models.CharField(help_text='Message envoyé quand le client clique', max_length=500)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_at_start', models.BooleanField(default=True, help_text='Afficher au démarrage de la conversation')),
            ],
            options={
                'db_table': 'chatbot_quick_replies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='chatbot.chatsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('keywords', models.TextField(blank=True, help_text='Mots-clés séparés par des virgules pour la détection automatique')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Plus la valeur est haute, plus la priorité est élevée')),
                ('view_count', models.IntegerField(default=0)),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='chatbot.faqcategory')),
            ],
            options={
                'db_table': 'faqs',
                'ordering': ['-priority', '-view_count'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'Client'), ('bot', 'Bot'), ('agent', 'Agent humain'), ('system', 'Système')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Texte'), ('quick_reply', 'Réponse rapide'), ('product_card', 'Carte produit'), ('order_status', 'Statut commande'), ('faq', 'FAQ'), ('escalation', 'Escalade')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='Extra data: product info, order info, etc.')),
                ('intent', models.CharField(blank=True, help_text='Detected intent', max_length=100)),
                ('confidence', models.FloatField(blank=True, help_text='NLP confidence score', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.faq')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
